version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - ENV_VARIABLE=your_value  
